### ISSUE TITLE
[enhancement] Load adata in as backed to save memory

### ISSUE THREAD

**Issue by arose20** [Issacgoh/scENTInEL#1]
Hi,

Within the `scentinel.load_adatas` function can you add an argument to load the data in backed format to save on memory usage?

This would be great when handling very large datasets. If there are downstream functions which require specific data loaded into memory maybe adding .to_memory() just to these specific cases with a notification to the user what has been added to memory would be very useful.

**Comment by Issacgoh** [comment]
Branch: prototype_v0.1.0
Merged to main: 473e747..658ca6d

Included the ability to read data in backed mode, also edited the KNN bayes sampler + plots to accept backed data. Unfortunately, training/projection has to be done with full data loaded in for now. This should significantly improve memory resource usage for the intial sampling mode in transductive runs. Only the sampled data is read into memory in full. 

![Screenshot 2023-07-28 at 19 43 55](https://github.com/Issacgoh/scENTInEL/assets/46449131/508ad441-f504-4985-94d3-29763d567f0f)
